/**
 * Biometric unlock (macOS Touch ID / Watch) — gates access to the wallet
 * passphrase, it does not replace it. The passphrase is stored in the user's
 * login keychain and only released by a small native helper after a
 * successful LocalAuthentication check. The scrypt/AES wallet encryption is
 * untouched, so the passphrase always remains the recovery path.
 *
 * The helper is a single Swift file embedded below, compiled on first use to
 * `~/.xpay/bin/xpay-biometric-<hash>` (requires Xcode Command Line Tools).
 * Embedding the source keeps the npm package dependency-free and lets tsc
 * ship it inside dist/ without a native build step at install time.
 */

import { join } from "node:path";
import { platform } from "node:os";
import { existsSync, mkdirSync, writeFileSync, readdirSync, unlinkSync } from "node:fs";
import { createHash } from "node:crypto";
import { execFileSync, execFile } from "node:child_process";
import { xpayHome } from "../profile/storage.js";

/** Keychain item identity — must match `kService` in the Swift source. */
export const KEYCHAIN_SERVICE = "com.xona-labs.xpay.wallet";

const HELPER_BASENAME = "xpay-biometric";

// Helper exit codes (mirrored in the Swift source).
const EXIT_OK = 0;
const EXIT_UNAVAILABLE = 2;
const EXIT_DENIED = 3;
const EXIT_NOT_FOUND = 4;

const SWIFT_SOURCE = `// xpay-biometric — generated by @xona-labs/xpay; do not edit.
import Foundation
import LocalAuthentication
import Security

let kService = "com.xona-labs.xpay.wallet"

func warn(_ msg: String) {
    FileHandle.standardError.write((msg + "\\n").data(using: .utf8)!)
}

func evaluate(_ reason: String) -> Bool {
    let ctx = LAContext()
    var error: NSError?
    guard ctx.canEvaluatePolicy(.deviceOwnerAuthenticationWithBiometrics, error: &error) else {
        warn(error?.localizedDescription ?? "biometry unavailable")
        exit(2)
    }
    let sem = DispatchSemaphore(value: 0)
    var ok = false
    ctx.evaluatePolicy(.deviceOwnerAuthenticationWithBiometrics, localizedReason: reason) { success, _ in
        ok = success
        sem.signal()
    }
    sem.wait()
    return ok
}

func baseQuery(_ account: String) -> [String: Any] {
    return [
        kSecClass as String: kSecClassGenericPassword,
        kSecAttrService as String: kService,
        kSecAttrAccount as String: account,
    ]
}

let args = CommandLine.arguments
guard args.count >= 2 else {
    warn("usage: xpay-biometric check | prompt <reason> | store <account> | read <account> <reason> | delete <account>")
    exit(1)
}

switch args[1] {
case "check":
    let ctx = LAContext()
    var error: NSError?
    guard ctx.canEvaluatePolicy(.deviceOwnerAuthenticationWithBiometrics, error: &error) else {
        warn(error?.localizedDescription ?? "biometry unavailable")
        exit(2)
    }
    print(ctx.biometryType == .faceID ? "faceid" : "touchid")
    exit(0)

case "prompt":
    let reason = args.count > 2 ? args[2] : "approve this action"
    exit(evaluate(reason) ? 0 : 3)

case "store":
    guard args.count > 2 else { warn("store: missing account"); exit(1) }
    let secret = FileHandle.standardInput.readDataToEndOfFile()
    guard !secret.isEmpty else { warn("store: empty secret on stdin"); exit(1) }
    SecItemDelete(baseQuery(args[2]) as CFDictionary)
    var add = baseQuery(args[2])
    add[kSecValueData as String] = secret
    add[kSecAttrLabel as String] = "xPay wallet passphrase (\\(args[2]))"
    let status = SecItemAdd(add as CFDictionary, nil)
    guard status == errSecSuccess else { warn("store: keychain error \\(status)"); exit(1) }
    exit(0)

case "read":
    guard args.count > 2 else { warn("read: missing account"); exit(1) }
    let reason = args.count > 3 ? args[3] : "unlock your xPay wallet"
    guard evaluate(reason) else { exit(3) }
    var query = baseQuery(args[2])
    query[kSecReturnData as String] = true
    query[kSecMatchLimit as String] = kSecMatchLimitOne
    var out: CFTypeRef?
    let status = SecItemCopyMatching(query as CFDictionary, &out)
    if status == errSecItemNotFound { warn("read: no stored passphrase for \\(args[2])"); exit(4) }
    guard status == errSecSuccess, let data = out as? Data else { warn("read: keychain error \\(status)"); exit(1) }
    FileHandle.standardOutput.write(data)
    exit(0)

case "delete":
    guard args.count > 2 else { warn("delete: missing account"); exit(1) }
    let status = SecItemDelete(baseQuery(args[2]) as CFDictionary)
    if status == errSecItemNotFound { exit(4) }
    guard status == errSecSuccess else { warn("delete: keychain error \\(status)"); exit(1) }
    exit(0)

default:
    warn("unknown command: \\(args[1])")
    exit(1)
}
`;

export type BiometryType = "touchid" | "faceid";

/** Thrown when biometrics can't work here at all (non-macOS, no swiftc, no enrolled biometry). */
export class BiometricUnavailableError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "BiometricUnavailableError";
  }
}

export function biometricPlatformSupported(): boolean {
  return platform() === "darwin";
}

function binDir(): string {
  return join(xpayHome(), "bin");
}

/**
 * Compile the helper if this exact source hasn't been compiled yet. The
 * binary name carries a source hash so upgrades recompile automatically;
 * stale versions are swept. Note: a freshly compiled binary triggers a new
 * macOS "allow keychain access" prompt on its first read — expected.
 */
function ensureHelper(): string {
  if (!biometricPlatformSupported()) {
    throw new BiometricUnavailableError("Biometric unlock is only supported on macOS.");
  }
  const hash = createHash("sha256").update(SWIFT_SOURCE).digest("hex").slice(0, 8);
  const bin = join(binDir(), `${HELPER_BASENAME}-${hash}`);
  if (existsSync(bin)) return bin;

  mkdirSync(binDir(), { recursive: true, mode: 0o700 });
  const src = join(binDir(), `${HELPER_BASENAME}.swift`);
  writeFileSync(src, SWIFT_SOURCE);
  try {
    execFileSync("swiftc", ["-O", "-o", bin, src], { stdio: ["ignore", "ignore", "pipe"] });
  } catch {
    throw new BiometricUnavailableError(
      "Could not compile the Touch ID helper — are the Xcode Command Line Tools installed? (xcode-select --install)",
    );
  }
  for (const f of readdirSync(binDir())) {
    if (f.startsWith(`${HELPER_BASENAME}-`) && f !== `${HELPER_BASENAME}-${hash}`) {
      try { unlinkSync(join(binDir(), f)); } catch { /* best effort */ }
    }
  }
  return bin;
}

interface HelperResult {
  code: number;
  stdout: string;
  stderr: string;
}

function runHelper(args: string[], input?: string): Promise<HelperResult> {
  const bin = ensureHelper();
  return new Promise((resolve) => {
    const child = execFile(
      bin,
      args,
      { encoding: "utf8", maxBuffer: 1024 * 1024 },
      (error, stdout, stderr) => {
        const code = error
          ? typeof (error as NodeJS.ErrnoException & { code?: unknown }).code === "number"
            ? ((error as unknown as { code: number }).code)
            : 1
          : 0;
        resolve({ code, stdout, stderr });
      },
    );
    if (input !== undefined) child.stdin?.write(input, "utf8");
    child.stdin?.end();
  });
}

/**
 * Probe biometry without showing a prompt. Returns the biometry type, or
 * null when the hardware/enrollment is missing. Throws
 * {@link BiometricUnavailableError} when the helper can't even be built.
 */
export async function biometricCheck(): Promise<BiometryType | null> {
  const r = await runHelper(["check"]);
  if (r.code === EXIT_OK) return r.stdout.trim() as BiometryType;
  if (r.code === EXIT_UNAVAILABLE) return null;
  throw new Error(`biometric check failed: ${r.stderr.trim() || `exit ${r.code}`}`);
}

/**
 * Show the system Touch ID sheet and return whether the user passed.
 * Throws {@link BiometricUnavailableError} when biometry can't be evaluated
 * (caller should fall back to its non-biometric path).
 */
export async function biometricPrompt(reason: string): Promise<boolean> {
  const r = await runHelper(["prompt", reason]);
  if (r.code === EXIT_OK) return true;
  if (r.code === EXIT_DENIED) return false;
  throw new BiometricUnavailableError(r.stderr.trim() || "biometry unavailable");
}

/** Save the passphrase for `account` (profile name) in the login keychain. */
export async function storeBiometricPassphrase(account: string, passphrase: string): Promise<void> {
  const r = await runHelper(["store", account], passphrase);
  if (r.code !== EXIT_OK) {
    throw new Error(`could not store passphrase in keychain: ${r.stderr.trim() || `exit ${r.code}`}`);
  }
}

/**
 * Biometric-gated read of the stored passphrase. Returns null when the user
 * cancels/fails the check or no passphrase is stored — both mean "fall back
 * to typing the passphrase". Throws {@link BiometricUnavailableError} when
 * biometry can't be evaluated at all.
 */
export async function readBiometricPassphrase(account: string, reason: string): Promise<string | null> {
  const r = await runHelper(["read", account, reason]);
  if (r.code === EXIT_OK) return r.stdout;
  if (r.code === EXIT_DENIED || r.code === EXIT_NOT_FOUND) return null;
  if (r.code === EXIT_UNAVAILABLE) {
    throw new BiometricUnavailableError(r.stderr.trim() || "biometry unavailable");
  }
  throw new Error(`keychain read failed: ${r.stderr.trim() || `exit ${r.code}`}`);
}

/** Remove the stored passphrase. Returns false if none was stored. */
export async function deleteBiometricPassphrase(account: string): Promise<boolean> {
  const r = await runHelper(["delete", account]);
  if (r.code === EXIT_OK) return true;
  if (r.code === EXIT_NOT_FOUND) return false;
  throw new Error(`keychain delete failed: ${r.stderr.trim() || `exit ${r.code}`}`);
}
